name: "Continuous Integration"

on:
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v2
          with:
            node-version: 12

        - run: npm ci

        - uses: wearerequired/lint-action@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            eslint: true

        - run: npm run test
        